### ISSUE TITLE
Problem with closed accounts

### ISSUE THREAD

**Issue by tobka777** [Andrej1b/zedd2#97]
Oft werden in Clarity Konten geschlossen, sodass eine Buchung nicht mehr möglich ist.

![image001](https://user-images.githubusercontent.com/40991903/224709706-403a7b64-7399-4840-a10f-a55bc7693d0e.png)

Wenn jedoch die ZeddApp einen Eintrag für ein geschlossenes Konto machen möchte, bricht die Übertragung ab.
![grafik](https://user-images.githubusercontent.com/40991903/224710084-6220a16b-e3a0-4a51-9d99-dc98fb0153dc.png)

# TODO
- [ ] Wenn Stunden für ein geschlossenes Konto eingefügt werden soll, sollen keinen Zeiten für dieses Konto, aber alle anderen Zeiten übertragen und gespeichert werden
- [ ] kein automatisches Vorlegen dieses Stundenzettels (wenn geschlossenes Konto enthält)
- [ ] Warnhinweis ausgeben: "Es konnten nicht alle Zeiten des Stundenzettels (27.02. - 28.02.) übertragen werden, weil mindestens ein Konto geschlossen war. Alle anderen Zeiten wurden übernommen und gespeichert. Der Stundenzettel wurde nicht automatisch vorgelegt."

**Comment by tobka777** [comment]
In Zukunft wird nur noch OTT und GTM unterstützt werden.
